/*RESGISTROS DE LAS AREAS*/
INSERT INTO AREA VALUES (SEQ_AREA.NEXTVAL, 'TELEFONIA');
INSERT INTO AREA (ID_AREA, DESCRIPCION) VALUES (SEQ_AREA.NEXTVAL, 'IMPLEMENTACION');
INSERT INTO AREA (ID_AREA, DESCRIPCION) VALUES (SEQ_AREA.NEXTVAL, 'CAPACITACION');
INSERT INTO AREA (ID_AREA, DESCRIPCION) VALUES (SEQ_AREA.NEXTVAL, 'CALIDAD');
INSERT INTO AREA (ID_AREA, DESCRIPCION) VALUES (SEQ_AREA.NEXTVAL, 'DESARROLLO');
COMMIT;

/*REGISTROS DE LAS ZONAS*/
INSERT INTO ZONA (ID_ZONA, DESCRIPCION) VALUES (SEQ_ZONA.NEXTVAL, 'DEL VALLE');
INSERT INTO ZONA (ID_ZONA, DESCRIPCION) VALUES (SEQ_ZONA.NEXTVAL, 'NAVARTE');
INSERT INTO ZONA (ID_ZONA, DESCRIPCION) VALUES (SEQ_ZONA.NEXTVAL, 'RELOX');
INSERT INTO ZONA (ID_ZONA, DESCRIPCION) VALUES (SEQ_ZONA.NEXTVAL, 'TORRES');
COMMIT;

/*REGISTROS DE LOS PUESTOS*/
INSERT INTO PUESTO (ID_PUESTO, DESCRIPCION) VALUES(SEQ_PUESTO.NEXTVAL, 'COORDINADOR');
INSERT INTO PUESTO (ID_PUESTO, DESCRIPCION) VALUES(SEQ_PUESTO.NEXTVAL, 'EMPLEADO');
COMMIT;

/* REGISTRO DE PERSONAS */
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, NO_CONTROL, ID_AREA, ID_ZONA, ID_PUESTO) 
    VALUES (SEQ_PERSONAS.NEXTVAL, 'EDGAR', 5654, 1, 1, 1);
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, NO_CONTROL, ID_AREA, ID_ZONA, ID_PUESTO) 
    VALUES (SEQ_PERSONAS.NEXTVAL, 'CESAR', 5652, 1, 1, 2);
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, NO_CONTROL, ID_AREA, ID_ZONA, ID_PUESTO) 
    VALUES (SEQ_PERSONAS.NEXTVAL, 'URIEL', 5650, 1, 2, 2);
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, NO_CONTROL, ID_AREA, ID_ZONA, ID_PUESTO) 
    VALUES (SEQ_PERSONAS.NEXTVAL, 'ISRAEL', 5648, 1, 3, 2);
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, NO_CONTROL, ID_AREA, ID_ZONA, ID_PUESTO) 
    VALUES (SEQ_PERSONAS.NEXTVAL, 'JOSUE', 5646, 3, 1, 1);
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, NO_CONTROL, ID_AREA, ID_ZONA, ID_PUESTO) 
    VALUES (SEQ_PERSONAS.NEXTVAL, 'FELIPE', 5644, 3, 4, 2);
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, NO_CONTROL, ID_AREA, ID_ZONA, ID_PUESTO) 
    VALUES (SEQ_PERSONAS.NEXTVAL, 'GUILLERMO', 5642, 2, 2, 1);
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, NO_CONTROL, ID_AREA, ID_ZONA, ID_PUESTO) 
    VALUES (SEQ_PERSONAS.NEXTVAL, 'ALI', 5640, 2, 3, 2);
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, NO_CONTROL, ID_AREA, ID_ZONA, ID_PUESTO) 
    VALUES (SEQ_PERSONAS.NEXTVAL, 'MAURO', 5638, 4, 1, 1);
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, NO_CONTROL, ID_AREA, ID_ZONA, ID_PUESTO) 
    VALUES (SEQ_PERSONAS.NEXTVAL, 'MIRIAM', 5636, 4, 4, 2);
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, NO_CONTROL, ID_AREA, ID_ZONA, ID_PUESTO) 
    VALUES (SEQ_PERSONAS.NEXTVAL, 'RICARDO', 5634, 5, 2, 2);
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, NO_CONTROL, ID_AREA, ID_ZONA, ID_PUESTO) 
    VALUES (SEQ_PERSONAS.NEXTVAL, 'LUIS', 5632, 5, 2, 1);
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, NO_CONTROL, ID_AREA, ID_ZONA, ID_PUESTO) 
    VALUES (SEQ_PERSONAS.NEXTVAL, 'JOSE', 5630, 5, 3, 2);
COMMIT;